version: "2"

services:
    buzzle:
        build:
            context: "."
            args:
                port: "${BUZZLE_PORT}"
        image: "toksaitov/buzzle"
        ports:
            - "${BUZZLE_PORT}:${BUZZLE_PORT}"
        env_file: ".env"
        depends_on:
            - "buzzle-db"
            - "buzzle-sess-db"

    buzzle-db:
        image: "mysql:5.7.29"
        command: "--character-set-server=utf8 --collation-server=utf8_general_ci"
        environment:
            MYSQL_ROOT_PASSWORD: "${BUZZLE_DB_PASS}"
            MYSQL_DATABASE: "${BUZZLE_DB_NAME}"
            MYSQL_USER: "${BUZZLE_DB_USER}"
            MYSQL_PASSWORD: "${BUZZLE_DB_PASS}"

    buzzle-sess-db:
        image: "redis:5.0.8"
        command: "redis-server --appendonly yes --requirepass ${BUZZLE_SESSION_DB_PASS}"
